language: python
sudo: required
os:
    - linux
    - osx
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
install:
    - pip install .
    - sudo pip install .
script:
    - sh '[ -e ~/0wned ]'
    - sh '[ -e /0wned ]'
